/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SADBloodBank;

import com.mysql.cj.jdbc.exceptions.CommunicationsException;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DeleteWindow extends javax.swing.JFrame {
     
    String strPhone;
    /**
     * Creates new form DeleteWindow
     */
    public DeleteWindow() {
        initComponents();
        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("com/SADBloodBank/icon/logo90.jpg"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeleteWindowName = new javax.swing.JLabel();
        lblDeleteWindowPhone = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDeleteWindowButtonYes = new javax.swing.JButton();
        btnDeleteWindowButtonNo = new javax.swing.JButton();
        txtDeleteWindowPassword = new javax.swing.JPasswordField();
        chkDeleteWindowShowPassword = new javax.swing.JCheckBox();
        btnDeleteWindowButtonNo2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Are You Sure ?");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDeleteWindowName.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblDeleteWindowName.setText("Name-:");
        getContentPane().add(lblDeleteWindowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblDeleteWindowPhone.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblDeleteWindowPhone.setText("Phone-:");
        getContentPane().add(lblDeleteWindowPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Password Is Needed To Delete Your Account!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setText("Password-:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel5.setText("Confirm To Delete Your Account?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        btnDeleteWindowButtonYes.setBackground(new java.awt.Color(255, 153, 153));
        btnDeleteWindowButtonYes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteWindowButtonYes.setText("Yes");
        btnDeleteWindowButtonYes.setPreferredSize(new java.awt.Dimension(84, 30));
        btnDeleteWindowButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWindowButtonYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteWindowButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 59, 30));

        btnDeleteWindowButtonNo.setBackground(new java.awt.Color(153, 204, 255));
        btnDeleteWindowButtonNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteWindowButtonNo.setText("No");
        btnDeleteWindowButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWindowButtonNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteWindowButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 57, 30));

        txtDeleteWindowPassword.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtDeleteWindowPassword.setEchoChar('*');
        txtDeleteWindowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteWindowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtDeleteWindowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, -1));

        chkDeleteWindowShowPassword.setText("Show Password");
        chkDeleteWindowShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDeleteWindowShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(chkDeleteWindowShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        btnDeleteWindowButtonNo2.setBackground(new java.awt.Color(153, 204, 255));
        btnDeleteWindowButtonNo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteWindowButtonNo2.setText("Clear");
        btnDeleteWindowButtonNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWindowButtonNo2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteWindowButtonNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SADBloodBank/icon/deletewindow.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDeleteWindowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteWindowPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteWindowPasswordActionPerformed

    private void chkDeleteWindowShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDeleteWindowShowPasswordActionPerformed
        if (this.chkDeleteWindowShowPassword.isSelected()) {
          this.txtDeleteWindowPassword.setEchoChar((char)0);
            } else {
            this.txtDeleteWindowPassword.setEchoChar('*');
           }    // TODO add your handling code here:
    }//GEN-LAST:event_chkDeleteWindowShowPasswordActionPerformed

    private void btnDeleteWindowButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteWindowButtonNoActionPerformed
     setVisible(false);
     }//GEN-LAST:event_btnDeleteWindowButtonNoActionPerformed

    private void btnDeleteWindowButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteWindowButtonYesActionPerformed

        if (this.txtDeleteWindowPassword.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Password!");
               this.txtDeleteWindowPassword.grabFocus();
             } else {
            String strPassword = this.txtDeleteWindowPassword.getText().trim();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/TWitwh2Zet","TWitwh2Zet","7XXP2w0UKM");
            Statement st = con.createStatement();
            int i = st.executeUpdate("DELETE FROM donor WHERE phone='" + this.strPhone + "' AND password='" + strPassword + "'");
        if (i == 1) {
             JOptionPane.showMessageDialog(this, "Your Record Has Been Deleted!");           
             setVisible(false);
            } else {
              JOptionPane.showMessageDialog(this, "Incorrect Password!");
              this.txtDeleteWindowPassword.setText("");
              chkDeleteWindowShowPassword.setSelected(false);
              this.txtDeleteWindowPassword.grabFocus();
            } 
        } catch (CommunicationsException e) {
        JOptionPane.showMessageDialog(this, "Please Connect Your Machine To Internet!");
         } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.toString());
          } 
     }     // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteWindowButtonYesActionPerformed

    private void btnDeleteWindowButtonNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteWindowButtonNo2ActionPerformed
          txtDeleteWindowPassword.setText("");
          chkDeleteWindowShowPassword.setSelected(false);
          txtDeleteWindowPassword.grabFocus();// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteWindowButtonNo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteWindowButtonNo;
    private javax.swing.JButton btnDeleteWindowButtonNo2;
    private javax.swing.JButton btnDeleteWindowButtonYes;
    private javax.swing.JCheckBox chkDeleteWindowShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    javax.swing.JLabel lblDeleteWindowName;
    javax.swing.JLabel lblDeleteWindowPhone;
    private javax.swing.JPasswordField txtDeleteWindowPassword;
    // End of variables declaration//GEN-END:variables
}
