/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SADBloodBank;

import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class DeleteRecord extends javax.swing.JFrame {

     DeleteWindow dw = new DeleteWindow();
     String strPhone;
     String strName;
    /**
     * Creates new form DeleteRecord
     */
    public DeleteRecord() {
        initComponents();
        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("com/SADBloodBank/icon/logo90.jpg"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDeleteRecordEmail = new javax.swing.JLabel();
        lblDeleteRecordHospital = new javax.swing.JLabel();
        lblDeleteRecordPhone = new javax.swing.JLabel();
        lblDeleteRecordName = new javax.swing.JLabel();
        lblDeleteRecordBloodGroup = new javax.swing.JLabel();
        btnDeleteRecordGoBack = new javax.swing.JButton();
        btnDeleteRecordDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Donor Found");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Your Record Has Been Matched!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Name-:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Blood Group-:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nearest Blood Bank-:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Phone-:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Email-:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblDeleteRecordEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeleteRecordEmail.setText("Email");
        getContentPane().add(lblDeleteRecordEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 240, -1));

        lblDeleteRecordHospital.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeleteRecordHospital.setText("Nearest Blood Bank");
        getContentPane().add(lblDeleteRecordHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 280, -1));

        lblDeleteRecordPhone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeleteRecordPhone.setText("Phone");
        getContentPane().add(lblDeleteRecordPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, -1));

        lblDeleteRecordName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeleteRecordName.setText("Name");
        getContentPane().add(lblDeleteRecordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 240, -1));

        lblDeleteRecordBloodGroup.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeleteRecordBloodGroup.setText("Blood Group");
        getContentPane().add(lblDeleteRecordBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 240, -1));

        btnDeleteRecordGoBack.setBackground(new java.awt.Color(153, 204, 255));
        btnDeleteRecordGoBack.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnDeleteRecordGoBack.setText("Go Back");
        btnDeleteRecordGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteRecordGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, 30));

        btnDeleteRecordDelete.setBackground(new java.awt.Color(255, 153, 153));
        btnDeleteRecordDelete.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnDeleteRecordDelete.setText("Delete");
        btnDeleteRecordDelete.setPreferredSize(new java.awt.Dimension(84, 30));
        btnDeleteRecordDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteRecordDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SADBloodBank/icon/bannerDeleteRecord.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteRecordGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordGoBackActionPerformed
         setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRecordGoBackActionPerformed

    private void btnDeleteRecordDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordDeleteActionPerformed
          setVisible(false);
            this.dw.lblDeleteWindowPhone.setText("Phone-: " + this.strPhone);
            this.dw.lblDeleteWindowName.setText("Name-: " + this.strName);
             this.dw.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRecordDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteRecordDelete;
    private javax.swing.JButton btnDeleteRecordGoBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    javax.swing.JLabel lblDeleteRecordBloodGroup;
    javax.swing.JLabel lblDeleteRecordEmail;
    javax.swing.JLabel lblDeleteRecordHospital;
    javax.swing.JLabel lblDeleteRecordName;
    javax.swing.JLabel lblDeleteRecordPhone;
    // End of variables declaration//GEN-END:variables
}
