/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SADBloodBank;

import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import com.mysql.cj.jdbc.exceptions.CommunicationsException;
/**
 *
 * @author DELL
 */
public class ForgottenPassword extends javax.swing.JFrame {
    /**
     * Creates new form ForgottenPassword
     */
    
    SADBloodBank sdb;
    public ForgottenPassword()
    {
        
    }
    public ForgottenPassword(SADBloodBank sdb) {
        this.sdb=sdb;
        this.setVisible(true);
        initComponents();
        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("com/SADBloodBank/icon/logo90.jpg"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtForgottenPasswordName = new javax.swing.JTextField();
        txtForgottenPasswordPhone = new javax.swing.JTextField();
        cmbForgottenPasswordBlood = new javax.swing.JComboBox<>();
        btnForgottenPasswordForgot = new javax.swing.JButton();
        btnForgottenPasswordClear = new javax.swing.JButton();
        btnForgottenPasswordExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Forgotten Password");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel1.setText("Enter Your Phone Number-:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel2.setText("Enter Name-:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel3.setText("Enter Your Blood Group-:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        txtForgottenPasswordName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtForgottenPasswordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 210, -1));

        txtForgottenPasswordPhone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtForgottenPasswordPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForgottenPasswordPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtForgottenPasswordPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 210, -1));

        cmbForgottenPasswordBlood.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbForgottenPasswordBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Please Select--]", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", " " }));
        cmbForgottenPasswordBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbForgottenPasswordBloodActionPerformed(evt);
            }
        });
        getContentPane().add(cmbForgottenPasswordBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 210, 30));

        btnForgottenPasswordForgot.setBackground(new java.awt.Color(153, 204, 255));
        btnForgottenPasswordForgot.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnForgottenPasswordForgot.setText("Forgot");
        btnForgottenPasswordForgot.setPreferredSize(new java.awt.Dimension(84, 30));
        btnForgottenPasswordForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgottenPasswordForgotActionPerformed(evt);
            }
        });
        getContentPane().add(btnForgottenPasswordForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        btnForgottenPasswordClear.setBackground(new java.awt.Color(153, 204, 255));
        btnForgottenPasswordClear.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnForgottenPasswordClear.setText("Clear");
        btnForgottenPasswordClear.setPreferredSize(new java.awt.Dimension(84, 30));
        btnForgottenPasswordClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgottenPasswordClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnForgottenPasswordClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        btnForgottenPasswordExit.setBackground(new java.awt.Color(255, 153, 153));
        btnForgottenPasswordExit.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnForgottenPasswordExit.setText("Exit");
        btnForgottenPasswordExit.setPreferredSize(new java.awt.Dimension(84, 30));
        btnForgottenPasswordExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgottenPasswordExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnForgottenPasswordExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 31));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SADBloodBank/icon/bannerforgetpassword.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbForgottenPasswordBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbForgottenPasswordBloodActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_cmbForgottenPasswordBloodActionPerformed

    private void btnForgottenPasswordForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgottenPasswordForgotActionPerformed
     if (fnForgottenPasswordNameValidate() && fnForgottenPasswordPhoneValidate() && fnForgottenPasswordBloodValidate())
      {     if (!fnForgottenPasswordForgot()) 
          {     
                JOptionPane.showMessageDialog(this, "Record Not Found!");
                this.txtForgottenPasswordName.grabFocus();                
           }
      }// TODO add your handling code here:
    }//GEN-LAST:event_btnForgottenPasswordForgotActionPerformed

    private void btnForgottenPasswordClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgottenPasswordClearActionPerformed
       fnForgottenPasswordClear();        // TODO add your handling code here:
    }//GEN-LAST:event_btnForgottenPasswordClearActionPerformed

    private void btnForgottenPasswordExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgottenPasswordExitActionPerformed
       new ExitWindow().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnForgottenPasswordExitActionPerformed

    private void txtForgottenPasswordPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForgottenPasswordPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForgottenPasswordPhoneActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

     private boolean fnForgottenPasswordForgot() {
        String name = this.txtForgottenPasswordName.getText().trim();
        String phone = this.txtForgottenPasswordPhone.getText().trim();
        String blood = (String)this.cmbForgottenPasswordBlood.getSelectedItem();
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/TWitwh2Zet","TWitwh2Zet","7XXP2w0UKM");
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM donor WHERE name='" + name + "' AND bloodgroup='" + blood + "' AND phone='" + phone + "'");
                if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Phone-: " + phone + "\nPassword-: " + rs.getString(10));
                fnForgottenPasswordClear();
                this.setVisible(false);
                return true;
                } 
            } catch (CommunicationsException e) {
                JOptionPane.showMessageDialog(this, "Please Connect Your Machine To Internet!");
                return true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
             } 
        return false;
  }
    
  private boolean fnForgottenPasswordNameValidate() {
         if (this.txtForgottenPasswordName.getText().trim().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Please Enter Your Name");
          this.txtForgottenPasswordName.grabFocus();
          return false;
         } 
         return true;
  }
  
  private boolean fnForgottenPasswordPhoneValidate() {
    if (this.txtForgottenPasswordPhone.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please Enter Your Phone Number");
      this.txtForgottenPasswordPhone.grabFocus();
      return false;
    } 
    String phoneNumber = this.txtForgottenPasswordPhone.getText().trim();
    String regex = "(0/91)?[6-9][0-9]{9}";
    boolean x = phoneNumber.matches(regex);
    if (!x) {
      JOptionPane.showMessageDialog(this, "Enter Valid Phone Number");
      this.txtForgottenPasswordPhone.grabFocus();
      return false;
    } 
    return true;
  }
  
  private boolean fnForgottenPasswordBloodValidate() {
    if (this.cmbForgottenPasswordBlood.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Please Select Your Blood Group");
      this.cmbForgottenPasswordBlood.grabFocus();
      return false;
    } 
    return true;
  }
  
  private void fnForgottenPasswordClear() {
    this.txtForgottenPasswordName.setText("");
    this.txtForgottenPasswordPhone.setText("");
    this.cmbForgottenPasswordBlood.setSelectedIndex(0);
    this.txtForgottenPasswordName.grabFocus();
  }
    
  private void dekh()
  {
      this.sdb.setVisible(true);
  }
  private void hata()
  {
      this.sdb.setVisible(false);
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgottenPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgottenPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgottenPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgottenPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgottenPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgottenPasswordClear;
    private javax.swing.JButton btnForgottenPasswordExit;
    private javax.swing.JButton btnForgottenPasswordForgot;
    private javax.swing.JComboBox<String> cmbForgottenPasswordBlood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtForgottenPasswordName;
    private javax.swing.JTextField txtForgottenPasswordPhone;
    // End of variables declaration//GEN-END:variables
}
