/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SADBloodBank;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import com.mysql.cj.jdbc.exceptions.CommunicationsException;

/**
 *
 * @author DELL
 */
public class UpdateRecord extends javax.swing.JFrame {
    /**
     * Creates new form UpdateRecord
     * @param id
     */
    SADBloodBank sad;
    Timer tm;
    int delay=100;
    
    public UpdateRecord()
    {
        
    }
    public UpdateRecord(String id,SADBloodBank sad) {
        initComponents();
        this.sad=sad;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("com/SADBloodBank/icon/logo90.jpg"));
        setIconImage(icon.getImage());
         tm=new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               java.util.Date d=new java.util.Date();
               DateFormat df=new SimpleDateFormat("hh:mm:ss");
               DateFormat af=new SimpleDateFormat("dd-MMMM-yyyy");
               String timeFormatted=df.format(d);
               String dateFormatted=af.format(d);
               lblUpdateRecordTime.setText(timeFormatted);
               lblUpdateRecordDate.setText(dateFormatted);               
            }
        });
        tm.start();
        
        fnUpdateRecordFetch(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cmbUpdateGender = new javax.swing.JComboBox<>();
        cmbUpdateAge = new javax.swing.JComboBox<>();
        cmbUpdateBlood = new javax.swing.JComboBox<>();
        cmbUpdateHospital = new javax.swing.JComboBox<>();
        txtUpdatePhone = new javax.swing.JTextField();
        txtUpdateEmail = new javax.swing.JTextField();
        btnUpdateUpdate = new javax.swing.JButton();
        btnUpdateClear = new javax.swing.JButton();
        btnUpdateGoBack = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taUpdateAddress = new javax.swing.JTextArea();
        cmbUpdateDisease = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        taUpdateDisease = new javax.swing.JTextArea();
        txtUpdatePassword = new javax.swing.JPasswordField();
        txtUpdateReEnterPassword = new javax.swing.JPasswordField();
        chkUpdateShowPassword = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        btnUpdateExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblUpdateRecordDate = new javax.swing.JLabel();
        lblUpdateRecordTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Update Donor Information");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel36.setText("1. Enter Your Name-:");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel37.setText("2. Select Your Gender-:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel38.setText("3. Select Your Age-:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel39.setText("4. Select Your Blood Group-:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel41.setText("5. Select Nearest Hospital-:");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel42.setText("6. Enter Your Phone Number-:");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel40.setText("7. Enter Your Email-:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        txtUpdateName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUpdateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUpdateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 250, 30));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel47.setText("8. Enter Your Address-:");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        cmbUpdateGender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbUpdateGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Please Select--]", "Male", "Female", "Other" }));
        cmbUpdateGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUpdateGenderActionPerformed(evt);
            }
        });
        jPanel1.add(cmbUpdateGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        cmbUpdateAge.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbUpdateAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Please Select--]", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65" }));
        cmbUpdateAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUpdateAgeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbUpdateAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        cmbUpdateBlood.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbUpdateBlood.setMaximumRowCount(9);
        cmbUpdateBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Please Select--]", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cmbUpdateBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUpdateBloodActionPerformed(evt);
            }
        });
        jPanel1.add(cmbUpdateBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        cmbUpdateHospital.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbUpdateHospital.setMaximumRowCount(10);
        cmbUpdateHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Please Select--]", "Chirayu Hospital BloodBank", "Gandhi Hospital BloodBank(Hamidia)", "Bansal Hospital BloodBank", "JK Hospital BloodBank", "Peoples Hospital BloodBank", "AIIMS Hospital BloodBank", "Kasturba Hospital BloodBank", "RedCross Hospital BloodBank", "JP 1250 Hospital BloodBank" }));
        cmbUpdateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUpdateHospitalActionPerformed(evt);
            }
        });
        jPanel1.add(cmbUpdateHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        txtUpdatePhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUpdatePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdatePhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtUpdatePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 250, 30));

        txtUpdateEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUpdateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtUpdateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 250, 30));

        btnUpdateUpdate.setBackground(new java.awt.Color(153, 204, 255));
        btnUpdateUpdate.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        btnUpdateUpdate.setText("Update");
        btnUpdateUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 110, 30));

        btnUpdateClear.setBackground(new java.awt.Color(153, 204, 255));
        btnUpdateClear.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        btnUpdateClear.setText("Clear");
        btnUpdateClear.setPreferredSize(new java.awt.Dimension(84, 30));
        btnUpdateClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 110, 30));

        btnUpdateGoBack.setBackground(new java.awt.Color(91, 174, 59));
        btnUpdateGoBack.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        btnUpdateGoBack.setText("Go Back");
        btnUpdateGoBack.setPreferredSize(new java.awt.Dimension(84, 30));
        btnUpdateGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGoBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 110, 30));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel45.setText("9. Any Disease In Past/Present-:");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel46.setText("10. Disease You Selected \\\"Yes\\\" Explain-:");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel44.setText("11. Enter New Password-:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel43.setText("12. Re-Enter Your New Password-:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        taUpdateAddress.setColumns(20);
        taUpdateAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        taUpdateAddress.setLineWrap(true);
        taUpdateAddress.setRows(5);
        taUpdateAddress.setText("\n");
        jScrollPane2.setViewportView(taUpdateAddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 160, 230, 60));

        cmbUpdateDisease.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbUpdateDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Please Select--]", "Yes", "No" }));
        cmbUpdateDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUpdateDiseaseActionPerformed(evt);
            }
        });
        jPanel1.add(cmbUpdateDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, -1, -1));

        taUpdateDisease.setColumns(20);
        taUpdateDisease.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        taUpdateDisease.setLineWrap(true);
        taUpdateDisease.setRows(5);
        taUpdateDisease.setText("\n");
        jScrollPane3.setViewportView(taUpdateDisease);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 300, 230, 60));

        txtUpdatePassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUpdatePassword.setEchoChar('*');
        jPanel1.add(txtUpdatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, 230, 30));

        txtUpdateReEnterPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUpdateReEnterPassword.setEchoChar('*');
        jPanel1.add(txtUpdateReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 230, 30));

        chkUpdateShowPassword.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        chkUpdateShowPassword.setForeground(new java.awt.Color(153, 0, 0));
        chkUpdateShowPassword.setText("Show Password");
        chkUpdateShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUpdateShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(chkUpdateShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Alert! You Can'nt Change Your Phone Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        btnUpdateExit.setBackground(new java.awt.Color(255, 153, 153));
        btnUpdateExit.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        btnUpdateExit.setText("Exit");
        btnUpdateExit.setPreferredSize(new java.awt.Dimension(84, 30));
        btnUpdateExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SADBloodBank/icon/logo90.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 90));

        lblUpdateRecordDate.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblUpdateRecordDate.setForeground(new java.awt.Color(153, 0, 0));
        lblUpdateRecordDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUpdateRecordDate.setText("01-January-2021");
        jPanel1.add(lblUpdateRecordDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 280, 30));

        lblUpdateRecordTime.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblUpdateRecordTime.setForeground(new java.awt.Color(153, 0, 0));
        lblUpdateRecordTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUpdateRecordTime.setText("00:00:00");
        jPanel1.add(lblUpdateRecordTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SADBloodBank/icon/bannerblue.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1150, 465));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 750));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
           setVisible(false);
          sad.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void txtUpdateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateNameActionPerformed

    private void cmbUpdateGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUpdateGenderActionPerformed

    }//GEN-LAST:event_cmbUpdateGenderActionPerformed

    private void cmbUpdateAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUpdateAgeActionPerformed

    }//GEN-LAST:event_cmbUpdateAgeActionPerformed

    private void cmbUpdateBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUpdateBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUpdateBloodActionPerformed

    private void cmbUpdateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUpdateHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUpdateHospitalActionPerformed

    private void txtUpdatePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdatePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatePhoneActionPerformed

    private void txtUpdateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateEmailActionPerformed

    private void btnUpdateUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUpdateActionPerformed
        if (updateFormCheck() == true && updateFormValidate() == true)
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/TWitwh2Zet","TWitwh2Zet","7XXP2w0UKM");
            PreparedStatement ps = con.prepareStatement("Update donor set name=?, gender=?, age=?, bloodgroup=?, nearestbloodbank=?, email=?, address=?, disease=?, password=? where phone=?");
            ps.setString(1, this.txtUpdateName.getText().trim());
            ps.setString(2, (String)this.cmbUpdateGender.getSelectedItem());
            ps.setInt(3, Integer.parseInt((String)this.cmbUpdateAge.getSelectedItem()));
            ps.setString(4, (String)this.cmbUpdateBlood.getSelectedItem());
            ps.setString(5, (String)this.cmbUpdateHospital.getSelectedItem());
            ps.setString(6, this.txtUpdateEmail.getText().trim());
            ps.setString(7, this.taUpdateAddress.getText().trim());
            if (this.cmbUpdateDisease.getSelectedIndex() == 1) {
                ps.setString(8, this.taUpdateDisease.getText().trim());
            } else {
                ps.setString(8, "No");
            }
            ps.setString(9, this.txtUpdatePassword.getText().trim());
            ps.setString(10, this.txtUpdatePhone.getText().trim());
            ps.executeUpdate();
            String dis;
            if (this.cmbUpdateDisease.getSelectedIndex() == 1) {
                dis= this.taUpdateDisease.getText().trim();
            } else {
                dis= "No";
            }
            sad.lblUserLoginName.setText(txtUpdateName.getText().trim());
            sad.lblUserLoginGender.setText((String)cmbUpdateGender.getSelectedItem());
            sad.lblUserLoginAge.setText((String)cmbUpdateAge.getSelectedItem());
            sad.lblUserLoginBloodGroup.setText((String)cmbUpdateBlood.getSelectedItem());
            sad.lblUserLoginNearestBloodBank.setText((String)cmbUpdateHospital.getSelectedItem());
            sad.lblUserLoginPhone.setText(txtUpdatePhone.getText().trim());
            sad.lblUserLoginEmail.setText(txtUpdateEmail.getText().trim());
            sad.lblUserLoginAddress.setText(taUpdateAddress.getText().trim());
            sad.lblUserLoginDisease.setText(dis);
            sad.txtUserLoginPassword.setText("");
            JOptionPane.showMessageDialog(this, "Name-:  " + this.txtUpdateName.getText().trim() + "\nGender-:  " + this.cmbUpdateGender.getSelectedItem() + "\nAge-:  "+ this.cmbUpdateAge.getSelectedItem() +"\nBlood-:  " + this.cmbUpdateBlood.getSelectedItem() + "\nNear Hospital-:  "+ this.cmbUpdateHospital.getSelectedItem()+"\nPhone-:  " + this.txtUpdatePhone.getText().trim() + "\nEmail-:  " + this.txtUpdateEmail.getText().trim() + "\nAddress-:  "+ this.taUpdateAddress.getText().trim()+ "\nDisease-:  "+dis+"\n \n \nThanks! Your Information Has Been Updated!");
            setVisible(false);
            sad.setVisible(true);
        } catch (CommunicationsException e) { 
            JOptionPane.showMessageDialog(this, "Please Connect Your Machine To Internet!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }           // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateUpdateActionPerformed

    private void btnUpdateClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateClearActionPerformed
        fnUpdateClear(); // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateClearActionPerformed

    private void btnUpdateGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGoBackActionPerformed
        setVisible(false);
        sad.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateGoBackActionPerformed

    private void cmbUpdateDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUpdateDiseaseActionPerformed
        if (this.cmbUpdateDisease.getSelectedIndex() == 0)
        this.taUpdateDisease.setVisible(false);
        if (this.cmbUpdateDisease.getSelectedIndex() == 1) {
            this.taUpdateDisease.setVisible(true);
            this.taUpdateDisease.setEditable(true);
        }
        if (this.cmbUpdateDisease.getSelectedIndex() == 2)
        this.taUpdateDisease.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_cmbUpdateDiseaseActionPerformed

    private void chkUpdateShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUpdateShowPasswordActionPerformed
        if (this.chkUpdateShowPassword.isSelected()) {
            this.txtUpdatePassword.setEchoChar((char)0);
            this.txtUpdateReEnterPassword.setEchoChar((char)0);
        } else {
            this.txtUpdatePassword.setEchoChar('*');
            this.txtUpdateReEnterPassword.setEchoChar('*');
        } // TODO add your handling code here:
    }//GEN-LAST:event_chkUpdateShowPasswordActionPerformed

    private void btnUpdateExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateExitActionPerformed
        new ExitWindow().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateExitActionPerformed

    private void fnUpdateRecordFetch(String id)
    {      try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/TWitwh2Zet","TWitwh2Zet","7XXP2w0UKM");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from donor where phone='"+id+"'");
            rs.next();
            txtUpdateName.setText(rs.getString(1));
            String s=rs.getString(2);
              if(s.equals("Male"))
                  cmbUpdateGender.setSelectedIndex(1);
              if(s.equals("Female"))
                  cmbUpdateGender.setSelectedIndex(2);
              if(s.equals("Other"))
                  cmbUpdateGender.setSelectedIndex(3);
            int i=rs.getInt(3);
            i=i-15;
            cmbUpdateAge.setSelectedIndex(i);
            s=rs.getString(4);
              if(s.equals("A+"))
                  cmbUpdateBlood.setSelectedIndex(1);
              if(s.equals("A-"))
                  cmbUpdateBlood.setSelectedIndex(2);
              if(s.equals("B+"))
                  cmbUpdateBlood.setSelectedIndex(3);
              if(s.equals("B-"))
                  cmbUpdateBlood.setSelectedIndex(4);
              if(s.equals("AB+"))
                  cmbUpdateBlood.setSelectedIndex(5);
              if(s.equals("AB-"))
                  cmbUpdateBlood.setSelectedIndex(6);
              if(s.equals("O+"))
                  cmbUpdateBlood.setSelectedIndex(7);
              if(s.equals("O-"))
                  cmbUpdateBlood.setSelectedIndex(7);
            s=rs.getString(5);
              if(s.equals("Chirayu Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(1);
              if(s.equals("Gandhi Hospital BloodBank(Hamidia)"))
                  cmbUpdateHospital.setSelectedIndex(2);
              if(s.equals("Bansal Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(3);
              if(s.equals("JK Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(4);
              if(s.equals("Peoples Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(5);
              if(s.equals("AIIMS Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(6);
              if(s.equals("Kasturba Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(7);
              if(s.equals("RedCross Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(8);
              if(s.equals("JP 1250 Hospital BloodBank"))
                  cmbUpdateHospital.setSelectedIndex(9);
            s=rs.getString(6);
               txtUpdatePhone.setText(s);
               txtUpdatePhone.setEditable(false);
            s=rs.getString(7);
               txtUpdateEmail.setText(s);
            s=rs.getString(8);
               taUpdateAddress.setText(s);
            s=rs.getString(9);
               if(s.equals("No"))
               { 
                   cmbUpdateDisease.setSelectedIndex(2);
               }
               else
               {
                   cmbUpdateDisease.setSelectedIndex(1);
                   taUpdateDisease.setVisible(true);
                   taUpdateDisease.setText(rs.getString(9));
               }
            s=rs.getString(10);
               txtUpdatePassword.setText(s);
               txtUpdateReEnterPassword.setText(s);
         } catch (CommunicationsException e) {
            JOptionPane.showMessageDialog(this, "Please Connect Your Machine To Internet!");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }  
    }
    
    private void fnUpdateClear() {
    txtUpdateName.setText("");
    cmbUpdateGender.setSelectedIndex(0);
    cmbUpdateAge.setSelectedIndex(0);
    cmbUpdateBlood.setSelectedIndex(0);
    cmbUpdateHospital.setSelectedIndex(0);
    txtUpdateEmail.setText("");
    taUpdateAddress.setText("");
    cmbUpdateDisease.setSelectedIndex(0);
    taUpdateDisease.setText("");
    txtUpdatePassword.setText("");
    txtUpdateReEnterPassword.setText("");
    txtUpdatePassword.setEchoChar('*');
    txtUpdateReEnterPassword.setEchoChar('*');
    chkUpdateShowPassword.setSelected(false);
    txtUpdateName.grabFocus();
  }
    
    private boolean updateFormCheck() {
    if (this.txtUpdateName.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please Enter Your Name");
      this.txtUpdateName.grabFocus();
      return false;
    } 
    if (this.txtUpdateName.getText().trim().length() > 30) {
      JOptionPane.showMessageDialog(this, "1. Name:\n\nMore Than 30 Characters Are Not Allowed!");
      this.txtUpdateName.grabFocus();
      return false;
    } 
    if (this.cmbUpdateGender.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Please Select Your Gender");
      this.cmbUpdateGender.grabFocus();
      return false;
    } 
    if (this.cmbUpdateAge.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Please Select Your Age");
      this.cmbUpdateAge.grabFocus();
      return false;
    } 
    if (this.cmbUpdateBlood.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Please Select Your Blood Group");
      this.cmbUpdateBlood.grabFocus();
      return false;
    } 
    if (this.cmbUpdateHospital.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Please Select A Nearest Hospital");
      this.cmbUpdateHospital.grabFocus();
      return false;
    } 
    if (this.txtUpdateEmail.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please Enter Your Email Address");
      this.txtUpdateEmail.grabFocus();
      return false;
    } 
    if (this.txtUpdateEmail.getText().trim().length() > 30) {
      JOptionPane.showMessageDialog(this, "7. Email:\n\nMore Than 30 Characters Are Not Allowed!");
      this.txtUpdateEmail.grabFocus();
      return false;
    } 
    if (this.taUpdateAddress.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please Enter Your Address");
      this.taUpdateAddress.grabFocus();
      return false;
    } 
    if (this.taUpdateAddress.getText().trim().length() > 30) {
      JOptionPane.showMessageDialog(this, "8. Address:\n\nMore Than 30 Characters Are Not Allowed!");
      this.taUpdateAddress.grabFocus();
      return false;
    } 
    if (this.cmbUpdateDisease.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Please Select Your Disease");
      this.cmbUpdateDisease.grabFocus();
      return false;
    } 
    if (this.cmbUpdateDisease.getSelectedIndex() == 1) {
      if (this.taUpdateDisease.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please Explain Your Disease");
        this.taUpdateDisease.grabFocus();
        return false;
      } 
      if (this.taUpdateDisease.getText().trim().length() > 30) {
        JOptionPane.showMessageDialog(this, "10. Disease:\n\nMore Than 30 Characters Are Not Allowed!");
        this.taUpdateDisease.grabFocus();
        return false;
      } 
    } 
    if (this.txtUpdatePassword.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please Enter Your New Password");
      this.txtUpdatePassword.grabFocus();
      return false;
    } 
    if (this.txtUpdateReEnterPassword.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please Re-Enter Your New Password");
      this.txtUpdateReEnterPassword.grabFocus();
      return false;
    } 
    if (!this.txtUpdatePassword.getText().trim().equals(this.txtUpdateReEnterPassword.getText())) {
      JOptionPane.showMessageDialog(this, "Both Passwords Not Match");
      this.txtUpdatePassword.grabFocus();
      return false;
    } 
    if (!this.txtUpdatePassword.getText().trim().isEmpty() && 
      this.txtUpdatePassword.getText().trim().length() > 20) {
      JOptionPane.showMessageDialog(this, "12. Password:\n13. Re-Enter Password\n\nMore Than 20 Characters Are Not Allowed!");
      this.txtUpdatePassword.grabFocus();
      return false;
    } 
    return true;
  }
    
    private boolean updateFormValidate() {
      String email = this.txtUpdateEmail.getText();
      boolean y = isValid(email);
      if (!y) {
        JOptionPane.showMessageDialog(this, "Enter Valid Email Address");
        this.txtUpdateEmail.grabFocus();
        return false;
      } 
     return y;
    }
    
    private static boolean isValid(String email) {
    String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
    return email.matches(regex);
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateClear;
    private javax.swing.JButton btnUpdateExit;
    private javax.swing.JButton btnUpdateGoBack;
    private javax.swing.JButton btnUpdateUpdate;
    private javax.swing.JCheckBox chkUpdateShowPassword;
    private javax.swing.JComboBox<String> cmbUpdateAge;
    private javax.swing.JComboBox<String> cmbUpdateBlood;
    private javax.swing.JComboBox<String> cmbUpdateDisease;
    private javax.swing.JComboBox<String> cmbUpdateGender;
    private javax.swing.JComboBox<String> cmbUpdateHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUpdateRecordDate;
    private javax.swing.JLabel lblUpdateRecordTime;
    private javax.swing.JTextArea taUpdateAddress;
    private javax.swing.JTextArea taUpdateDisease;
    private javax.swing.JTextField txtUpdateEmail;
    private javax.swing.JTextField txtUpdateName;
    private javax.swing.JPasswordField txtUpdatePassword;
    private javax.swing.JTextField txtUpdatePhone;
    private javax.swing.JPasswordField txtUpdateReEnterPassword;
    // End of variables declaration//GEN-END:variables
}
